before_install:
  - phpenv config-rm xdebug.ini

sudo: false

language: php

php:
  - 7.2.0
  - 7.2
  - 7.1.12
  - 7.1.0
  - 7.1
  - 7.0.26
  - 7.0.0
  - 7.0
  - 5.6.31
  - 5.6.0
  - 5.6
  - 5.5.38
  - 5.5
  - 5.4.45
  - 5.4
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=trunk WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=1

services:
  - mysql

addons:
  - mariadb: '5.5'
  - mariadb: '10.0'

cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: 5.6.32
  fast_finish: true

script:
  - find . \( -name '*.php' \) -exec php -lf {} \;
  - ./bin/test.sh

notifications:
  email: false
